import AppWrappper from "@/components/AppWrapper/index";
import Header from "@/components/header/Header";
import type { Metadata } from "next";
import "./globals.css";

import ReduxProvider from "@/components/ReduxProvider";

export const metadata: Metadata = {
  title: "FINTEX",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ReduxProvider>
        <Header/>
        <AppWrappper>{children}</AppWrappper>
        </ReduxProvider>
      </body>
    </html>
  );
}
